tags:
  - name: Auth 
    description: Auth Api for Sign-In & Sign-Up
  - name: Blog 
    description: Blog CRUD Apis
  - name: Category 
    description: Category CRUD Apis 
  - name: Comment 
    description: Comment creation APi
components:
  schemas:
    Blog:
      type: object
      properties:
        title:
          type: string
          example: Some Title
        long_desc:
          type: string
          example: Some long_desc
        short_desc:
          type: string
          example: Some short_desc
        